/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tree.gltf 
Author: TechArtBGN (https://sketchfab.com/TechArtBGN)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tree-gn-40da979cb23f492583ec89c4196cff4e
Title: Tree GN
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tree.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.TreeGen_ClusterB_0.geometry} material={materials.ClusterB} />
          <mesh geometry={nodes.TreeGen_VinesB_0.geometry} material={materials.VinesB} />
          <mesh geometry={nodes.TreeGen_ClusterB2_0.geometry} material={materials.ClusterB2} />
          <mesh geometry={nodes.TreeGen_BarkB_0.geometry} material={materials.BarkB} />
          <mesh geometry={nodes.TreeGen_PruneB_0.geometry} material={materials.PruneB} />
          <mesh geometry={nodes.TreeGen_CortexB_0.geometry} material={materials.CortexB} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tree.gltf')
